PYTHON_FILES := $(shell find . -name "*.py" ! -name "__init__.py" ! -name "manage.py")

all: $(PYTHON_FILES)

clean-build:
	@ echo "Clean build files here"

clean:
	@ rm -rf ./app

run: clean
	@ cp -R ../app .
	@ find . -iname "*.py[co]" -delete
	@ $(MAKE) && $(MAKE) clean-build

.DEFAULT: all
.PHONY: all clean clean-build run
